linters:
- import:
    packages: ['iodata']
- namespace:
    filefilter: ['- */__init__.py', '- */test_*.py', '- *setup.py', '- tools/*',
                 '- */formats/*.py', '+ *.py', '+ *.pyx']
- pylint:
- pycodestyle:
    config: .pycodestylerc
- pydocstyle:
- whitespace:
    filefilter: ['- iodata/test/data/*']
