project:
  name: iodata
  conda_requirements: [sympy]
  packages:
    - conda_name: iodata
      tools:
        - write-py-version
        - cardboardlint-static
        - build-py-inplace
        - cardboardlint-dynamic
        - pytest
        - build-sphinx-doc
        - build-py-source
        - build-conda
        - deploy-pypi
        - deploy-conda
        - deploy-github
