package:
  version: "{{ PROJECT_VERSION }}"
  name: 'iodata'

source:
  path: ../../

build:
  number: 0
  string: py{{ CONDA_PY }}_1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - numpy >=1.0
    - cython >=0.24.1
    - setuptools
    - pytest
  run:
    - python
    - scipy
    - importlib_resources
test:
  requires:
    - python
    - pytest
  commands:
    - conda inspect linkages iodata
    - pytest --pyargs iodata

about:
  home: https://github.com/theochem/iodata
  license: GNU Version 3
