package:
  version: "{{ PROJECT_VERSION }}"
  name: 'iodata'

source:
  path: ../../

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - numpy
    - scipy
    - cython >=0.24.1
    - setuptools
    - nose
    - gcc     # [ not win ]
  run:
    - python
    - numpy
    - scipy
    - nose
    - libgcc  # [ not win ]

about:
  home: https://github.com/theochem/iodata
  license: GNU Version 3
