package:
  version: "{{ PROJECT_VERSION }}"
  name: 'iodata'

source:
  path: ../../

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - numpy
    - cython >=0.24.1
    - setuptools
    - nose
  run:
    - scipy

about:
  home: https://github.com/theochem/iodata
  license: GNU Version 3
